### ISSUE TITLE
Suggest how you collected exe

### ISSUE THREAD

**Issue by izzzzzi** [ScriptSmith/reaper#8]
Hello, a little off topic, but tell me what you collected the sorts in exe?)

**Comment by ScriptSmith** [comment]
[Pyinstaller](https://github.com/pyinstaller/pyinstaller)

You can see the scripts used to create it in [scripts/](https://github.com/ScriptSmith/reaper/tree/master/scripts). These are specific to the workstation that I build Reaper on, so don't just copy them verbatim because they won't work for your own projects (and they don't really use best practices).

The pyinstaller documentation is pretty good, have a go at building executables for 'hello, world' type programs first before you try something complicated like Reaper.

In the future, releases will be built with CI using Travis and Appveyor to get Windows, macOS, and Linux builds. I'll probably also switch over to [InstallBuilder](https://installbuilder.bitrock.com/) to do auto-updates
